import streamlit as st
import cv2
import pytesseract
from PIL import Image
import numpy as np
import io
import json
import base64
import requests

# Tesseract executable path. You'll need to set this if it's not in your PATH.
try:
    pytesseract.pytesseract.tesseract_cmd = r'/usr/local/bin/tesseract'
except FileNotFoundError:
    st.warning("Pytesseract executable not found. Please make sure Tesseract is installed and the path is correct.")

def image_to_base64(pil_image):
    """
    Converts a PIL Image object to a base64-encoded string.
    This is necessary to send the image data to the Gemini API.
    """
    buffered = io.BytesIO()
    pil_image.save(buffered, format="PNG")
    img_str = base64.b64encode(buffered.getvalue()).decode('utf-8')
    return img_str

def call_gemini_api_for_tikz(api_key, prompt, base64_image):
    """
    Makes a call to the Gemini API with the given prompt and image.
    """
    # The payload for a multimodal request
    payload = {
        "contents": [
            {
                "parts": [
                    {"text": prompt},
                    {
                        "inlineData": {
                            "mimeType": "image/png",
                            "data": base64_image
                        }
                    }
                ]
            }
        ]
    }
    
    # The API endpoint for the specified model
    api_url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-05-20:generateContent?key={api_key}"

    try:
        response = requests.post(api_url, json=payload, timeout=60)
        response.raise_for_status()  # Raise an HTTPError for bad responses (4xx or 5xx)
        result = response.json()

        # Check for candidates and return the generated text
        if 'candidates' in result and len(result['candidates']) > 0:
            return result['candidates'][0]['content']['parts'][0]['text']
        else:
            return "No text generated by the model."

    except requests.exceptions.RequestException as e:
        st.error(f"An API error occurred: {e}")
        st.error(f"Response content: {response.text}")
        return None
    except Exception as e:
        st.error(f"An unexpected error occurred: {e}")
        return None

def generate_tikz_code(image, api_key):
    """
    This is the core function demonstrating the LLM pipeline.
    It performs OCR and then builds a prompt for the LLM with the image data.
    """
    if not api_key:
        st.error("Please enter your Gemini API key to proceed.")
        return None, None

    try:
        # Convert the PIL image to a NumPy array for OpenCV
        open_cv_image = np.array(image.convert('RGB'))
        open_cv_image = open_cv_image[:, :, ::-1].copy() # Convert RGB to BGR

        # --- Image Preprocessing and OCR ---
        gray_image = cv2.cvtColor(open_cv_image, cv2.COLOR_BGR2GRAY)
        text_from_image = pytesseract.image_to_string(gray_image).strip()
        
        # --- Prepare the prompt for the LLM ---
        prompt = f"""
        You are an expert in generating LaTeX code for commutative diagrams using the tikz-cd package.
        The following text was extracted from an image of a commutative diagram:

        "{text_from_image}"

        Based on the image provided, generate the complete and correct TikZ-cd LaTeX code to reproduce the diagram.
        Ensure the code is enclosed within a document class and includes the necessary packages.
        Make sure the diagram is centered. Do not add any extra explanations or text, just the full LaTeX code.
        If you cannot infer the diagram, provide a basic 2x2 diagram as a default.
        """
        
        # --- Convert image to base64 ---
        base64_image = image_to_base64(image)
        
        st.write("### Generated Prompt for the LLM:")
        st.code(prompt)

        # --- Call the Gemini API ---
        st.info("Calling Gemini API to generate TikZ-cd code...")
        tikz_output = call_gemini_api_for_tikz(api_key, prompt, base64_image)
        
        return tikz_output, open_cv_image

    except Exception as e:
        st.error(f"An error occurred during image processing or API call: {e}")
        return None, None

# --- Streamlit UI ---

st.set_page_config(page_title="Diagram to TikZ-cd Converter", layout="centered")

st.title("Diagram to TikZ-cd Converter")
st.markdown("Upload an image of a commutative diagram and get the LaTeX code, powered by the Gemini API.")

# Input for the user's API key
api_key = st.text_input("Enter your Gemini API key:", type="password")
st.markdown("Don't have a key? Get one for free from the [Gemini API Console](https://aistudio.google.com/app/apikey).")

uploaded_file = st.file_uploader("Choose an image...", type=["png", "jpg", "jpeg"])

if uploaded_file is not None:
    # Read the image file and convert to a PIL Image object
    image_bytes = io.BytesIO(uploaded_file.getvalue())
    pil_image = Image.open(image_bytes)

    # Display the uploaded image
    st.write("### Original Diagram")
    st.image(pil_image, caption="Uploaded Image", use_column_width=True)

    st.markdown("---")

    # Generate the TikZ-cd code and display the processed image
    if st.button("Generate Code"):
        with st.spinner("Processing image and generating code..."):
            tikz_output, processed_image = generate_tikz_code(pil_image, api_key)

        if tikz_output and processed_image is not None:
            st.write("### Generated TikZ-cd Code")
            st.code(tikz_output, language='latex')

            # Add a download button for the LaTeX code
            st.download_button(
                label="Download TikZ Code",
                data=tikz_output,
                file_name="diagram.tex",
                mime="text/plain"
            )
